### ISSUE TITLE
Implementing `fpm` (Fortran Package Manager)

### ISSUE THREAD

**Issue by MatthAlex** [noaa-oar-arl/Fyaml#11]
## Description

[FPM](https://fpm.fortran-lang.org/) has seen some great adoption the past few years and would be great if `Fyaml` supported it. 

### Context

I wondered if `Fyaml` builds with it, so I introduced a simple `fpm.toml` file:

```toml
name = "fyaml"
version = "2025.0.1"
license = "LICENSE"
author = ""
maintainer = ""
copyright = ""

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
```

From my own project's `fpm.toml`:

```toml
[dependencies]
fyaml = { git="git@github.com:MatthAlex/Fyaml.git", branch = "feature/add-fpm" }
```

Then simply `fpm build`
